services:
  portfolio:
    image: nginx:alpine
    container_name: portfolio
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - ms_npm_network

networks:
  ms_npm_network:
    external: true
